# Generated by Django 6.0.2 on 2026-02-28 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_metadata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('formula', 'Formula'), ('link', 'Link')], default='text', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ui_x', models.IntegerField(default=350)),
                ('ui_y', models.IntegerField(default=200)),
                ('color', models.CharField(default='bg-blue-500', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextColumn',
            fields=[
                ('column_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.column')),
                ('max_length', models.IntegerField(default=255)),
            ],
            bases=('builder.column',),
        ),
        migrations.CreateModel(
            name='ColumnDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_deps', to='builder.column')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='builder.table'),
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Boss (Owner)'), ('ADMIN', 'Administrator'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TablePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit_data', models.BooleanField(default=False)),
                ('can_edit_structure', models.BooleanField(default=False)),
                ('can_view_formulas', models.BooleanField(default=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.table')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='builder.workspacemember')),
            ],
        ),
        migrations.CreateModel(
            name='LinkColumn',
            fields=[
                ('column_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.column')),
                ('relation_type', models.CharField(default='one_to_many', max_length=20)),
                ('target_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='builder.table')),
            ],
            bases=('builder.column',),
        ),
        migrations.CreateModel(
            name='NumberColumn',
            fields=[
                ('column_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.column')),
                ('decimals', models.IntegerField(default=2)),
                ('is_formula', models.BooleanField(default=False)),
                ('raw_formula', models.TextField(blank=True, null=True)),
                ('dependencies', models.ManyToManyField(related_name='dependent_formulas', through='builder.ColumnDependency', through_fields=('target_column', 'source_column'), to='builder.column')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_metadata.unit')),
            ],
            bases=('builder.column',),
        ),
        migrations.AddField(
            model_name='columndependency',
            name='target_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_deps', to='builder.numbercolumn'),
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='builder.table')),
            ],
            options={
                'indexes': [models.Index(fields=['data'], name='row_data_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(fields=('user',), name='uniq_member_per_tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='tablepermission',
            unique_together={('member', 'table')},
        ),
    ]
